### PR TITLE
Create a new socket each time we report to graphite.

### PR DESCRIPTION
**Pull request by adamdecaf**
This commit reverts https://github.com/dropwizard/metrics/commit/d42bc7f6c20fb33bf9cc6c31e9a649418e76cc01 as it was seemingly causing us issues. 

FYI I've released this over at http://nexus.banno.com/nexus/content/repositories/thirdparty/io/dropwizard/metrics/metrics-graphite/3.1.2-banno-1.0.0-java7/

Related issue: https://github.com/dropwizard/metrics/issues/814

### CODE REVIEW

**Comment by zcox** [comment]
Hi @adamdecaf - when I was looking at this recently, I was thinking maybe each call to `GraphiteReporter.report` should result in one socket (udp or tcp) being opened to the Graphite server, used for all metrics being reported (i.e. each call to `GraphiteSender.send`) and then closed when all metrics have been reported. 

I'm assuming that `GraphiteReporter.report` gets called once per minute (or whatever is configured) with params containing every single metric in the entire system, sends all metrics to Graphite really quickly, then does nothing again for another minute until it's called again. Does that seem accurate? 

If that's the way it works, it might be good to reuse that socket/connection throughout the same `GraphiteReporter.report` call since there could presumably be lots of metrics sent to Graphite in that call. It might be costly to open/use/close a single socket/connection for each individual metric to send.

The `GraphiteSender` API doesn't make it straightforward to take this approach though. `GraphiteReporter.report` seems to call `isConnected` and `connect` first, then call `send` many times, and then finally calls `flush` at the end, so maybe those calls could be used in a `GraphiteSender` impl to create, use and then close the socket per single call to `GraphiteReporter.report`?

**Comment by adamdecaf** [comment]
@zcox Yea, that's probably the better approach. `send()` is probably too low level for this. I'll fix that up today.

**Comment by zcox** [comment]
:+1:

**Comment by adamdecaf** [comment]
@zcox I'm gonna go ahead and publish this and see how it works out.

**Comment by zcox** [comment]
@adamdecaf can't wait to see how it works

**Comment by DustinChaloupka** [comment]
@adamdecaf I take it this worked out when you tried it?

**Comment by adamdecaf** [comment]
@DustinChaloupka yea, I got the unit tests to all pass fine. Haven't tried it with graphite in big yet though.

**Comment by DustinChaloupka** [comment]
:+1:

**Comment by adamdecaf** [comment]
Closing this because our other fix has worked thus far.

**Comment by joelittlejohn** [comment]
Hi @adamdecaf would you be able to elaborate a bit on what you meant by your 'other' fix? Do you still have a PR somewhere waiting to be merged into https://github.com/dropwizard/metrics?

We're finding that our hosts fail to report metrics whenever there is any kind of temporary communication failure with carbon. The graphite reporter fails to connect from that point onward. The connection to carbon is simply not robust enough since https://github.com/dropwizard/metrics/commit/d42bc7f6c20fb33bf9cc6c31e9a649418e76cc01 was applied.

I see you opened https://github.com/dropwizard/metrics/issues/814 - are you sticking with a forked version of dropwizard/metrics now or have you found some other way to work around this? Cheers

**Comment by adamdecaf** [comment]
@joelittlejohn We're routing metrics through haproxy. We had a bit of configuration that we tweaked to allow for better timing windows and payloads.

**Pull request closed without merging**
